# -*- coding: utf-8 -*-
"""suc_n8n_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YY1Z0dmsQYTC_JEFUUIbzOQqSDsH0sAV
"""

!pip install pyngrok

!git clone https://github.com/n8n-io/n8n.git

# Commented out IPython magic to ensure Python compatibility.
# %cd n8n



from pyngrok import ngrok
import threading
import time

ngrok_token = "XXXXXXXXXXX"
ngrok.set_auth_token(ngrok_token)

# Start ngrok in a separate thread to avoid blocking
def start_ngrok():
    public_url = ngrok.connect(5678).public_url
    print(f"🚀 Ngrok Tunnel Open: {public_url}")

ngrok_thread = threading.Thread(target=start_ngrok)
ngrok_thread.start()

# Wait for ngrok to start (optional)
time.sleep(5)

!npx n8n

from pyngrok import ngrok
import threading
import time

ngrok_token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
ngrok.set_auth_token(ngrok_token)

# Start ngrok in a separate thread to avoid blocking
def start_ngrok():
    public_url = ngrok.connect(5678).public_url
    print(f"🚀 Ngrok Tunnel Open: {public_url}")

ngrok_thread = threading.Thread(target=start_ngrok)
ngrok_thread.start()

# Wait for ngrok to start (optional)
time.sleep(5)

!npx n8n